import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  getDocs,
  onSnapshot,
  orderBy,
  query,
  setDoc,
  Timestamp,
  updateDoc,
  where,
  type Unsubscribe,
} from "firebase/firestore";
import {
  assertClaimAllowed,
  type Bill,
  type BillId,
  type Claim,
  type ClaimId,
} from "@owez/shared";
import { getFirebase } from "./firebase";

/**
 * Data access for bills + claims.
 *
 * Identifiers: billId is a crypto.randomUUID(). Item ids are short ids from
 * makeId(). Claim doc ids are auto-generated by Firestore — each claim
 * stores its `claimerId` as a field, which the security rules pin to
 * `request.auth.uid`.
 */

export function newBillId(): BillId {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789";
  let id = "";
  const bytes = crypto.getRandomValues(new Uint8Array(10));
  for (const b of bytes) id += chars[b % chars.length];
  return id;
}

export function makeId(): string {
  // Short id for line items — UUID is overkill here. 8 url-safe chars.
  return Math.random().toString(36).slice(2, 10);
}

/** Write a new bill doc. The caller must already be signed in with a real user. */
export async function createBill(bill: Bill): Promise<void> {
  const { db } = getFirebase();
  await setDoc(doc(db, "bills", bill.id), bill);
}

/** Update an existing bill (creator only, enforced by rules). */
export async function updateBill(bill: Bill): Promise<void> {
  const { db } = getFirebase();
  await setDoc(doc(db, "bills", bill.id), bill);
}

export async function deleteBill(billId: BillId): Promise<void> {
  const { db } = getFirebase();
  await deleteDoc(doc(db, "bills", billId));
}

/** Subscribe to a bill doc. Returns an unsubscribe function. */
export function subscribeToBill(
  billId: BillId,
  onChange: (bill: Bill | null) => void,
): Unsubscribe {
  const { db } = getFirebase();
  return onSnapshot(doc(db, "bills", billId), (snap) => {
    if (!snap.exists()) {
      onChange(null);
      return;
    }
    onChange(fromFirestore(snap.data()));
  });
}

/**
 * Subscribe to every bill the given user has created, newest first.
 *
 * The error callback fires when the composite index is still building after
 * a fresh deploy — callers should treat that as an empty list rather than
 * hanging on "Loading…" forever. Once the index finishes materializing the
 * listener will succeed on its own.
 */
export function subscribeToMyBills(
  creatorId: string,
  onChange: (bills: Bill[]) => void,
  onError?: (err: Error) => void,
): Unsubscribe {
  const { db } = getFirebase();
  const q = query(
    collection(db, "bills"),
    where("creatorId", "==", creatorId),
    orderBy("createdAt", "desc"),
  );
  return onSnapshot(
    q,
    (snap) => {
      const bills: Bill[] = [];
      snap.forEach((d) => bills.push(fromFirestore(d.data())));
      onChange(bills);
    },
    (err) => onError?.(err),
  );
}

/** Subscribe to every claim on a bill as a flat array. */
export function subscribeToClaims(
  billId: BillId,
  onChange: (claims: Claim[]) => void,
): Unsubscribe {
  const { db } = getFirebase();
  const q = query(
    collection(db, "bills", billId, "claims"),
    orderBy("createdAt", "asc"),
  );
  return onSnapshot(q, (snap) => {
    const claims: Claim[] = snap.docs.map((d) => claimFromDoc(d.id, d.data()));
    onChange(claims);
  });
}

/** One-shot fetch of claims — used by dashboard for aggregated totals. */
export async function getClaimsOnce(billId: BillId): Promise<Claim[]> {
  const { db } = getFirebase();
  const snap = await getDocs(collection(db, "bills", billId, "claims"));
  return snap.docs.map((d) => claimFromDoc(d.id, d.data()));
}

/**
 * Create a new claim on a specific (itemId, unitIndex) pair. Validates
 * against existing claims on the same unit first so concurrent writes can't
 * over-subscribe. Not a true transaction — Firestore's web SDK can't
 * transactionally read a collection — but the race window is narrow enough
 * for the scale we care about.
 */
export async function claimItemUnit(
  billId: BillId,
  data: Omit<Claim, "id" | "createdAt">,
): Promise<ClaimId> {
  const { db } = getFirebase();
  const claimsCol = collection(db, "bills", billId, "claims");

  // Pre-flight conflict check.
  const snap = await getDocs(claimsCol);
  const onUnit = snap.docs
    .map((d) => claimFromDoc(d.id, d.data()))
    .filter(
      (c) => c.itemId === data.itemId && c.unitIndex === data.unitIndex,
    );
  assertClaimAllowed(onUnit, {
    portions: data.portions,
    splitInto: data.splitInto,
  });

  const payload: Record<string, unknown> = {
    itemId: data.itemId,
    unitIndex: data.unitIndex,
    portions: data.portions,
    splitInto: data.splitInto,
    claimerId: data.claimerId,
    name: data.name,
    initials: data.initials,
    createdAt: Date.now(),
  };
  if (data.photoURL) payload.photoURL = data.photoURL;

  const ref = await addDoc(claimsCol, payload);
  return ref.id;
}

/** Update an existing claim's portions/splitInto. Rules allow the claimer only. */
export async function updateClaimDoc(
  billId: BillId,
  claimId: ClaimId,
  data: { portions: number; splitInto: number },
): Promise<void> {
  const { db } = getFirebase();
  await updateDoc(doc(db, "bills", billId, "claims", claimId), data);
}

/** Delete a single claim doc. Rules allow the claimer or the bill creator. */
export async function deleteClaimDoc(
  billId: BillId,
  claimId: ClaimId,
): Promise<void> {
  const { db } = getFirebase();
  await deleteDoc(doc(db, "bills", billId, "claims", claimId));
}

/* ---------- Firestore ↔ TS shape glue ---------- */

function fromFirestore(data: Record<string, unknown>): Bill {
  const createdAt =
    data.createdAt instanceof Timestamp
      ? data.createdAt.toMillis()
      : typeof data.createdAt === "number"
        ? data.createdAt
        : Date.now();

  return {
    id: String(data.id ?? ""),
    creatorId: String(data.creatorId ?? ""),
    creatorName:
      typeof data.creatorName === "string" ? data.creatorName : undefined,
    creatorPhotoURL:
      typeof data.creatorPhotoURL === "string"
        ? data.creatorPhotoURL
        : undefined,
    createdAt,
    title: typeof data.title === "string" ? data.title : undefined,
    items: Array.isArray(data.items) ? (data.items as Bill["items"]) : [],
    subtotalCents: Number(data.subtotalCents ?? 0),
    taxCents: Number(data.taxCents ?? 0),
    tipCents: Number(data.tipCents ?? 0),
    totalCents: Number(data.totalCents ?? 0),
    paymentMethods:
      (data.paymentMethods as Bill["paymentMethods"] | undefined) ?? {},
  };
}

function claimFromDoc(id: string, data: Record<string, unknown>): Claim {
  return {
    id,
    itemId: String(data.itemId ?? ""),
    unitIndex: Number(data.unitIndex ?? 0),
    portions: Number(data.portions ?? 1),
    splitInto: Number(data.splitInto ?? 1),
    claimerId: String(data.claimerId ?? ""),
    name: typeof data.name === "string" ? data.name : "",
    initials: typeof data.initials === "string" ? data.initials : "",
    createdAt:
      data.createdAt instanceof Timestamp
        ? data.createdAt.toMillis()
        : typeof data.createdAt === "number"
          ? data.createdAt
          : Date.now(),
    photoURL: typeof data.photoURL === "string" ? data.photoURL : undefined,
  };
}
