import {
  addDoc,
  arrayUnion,
  collection,
  collectionGroup,
  deleteDoc,
  doc,
  getDocs,
  onSnapshot,
  orderBy,
  query,
  setDoc,
  Timestamp,
  updateDoc,
  where,
  type Unsubscribe,
} from "firebase/firestore";
import {
  assertClaimAllowed,
  claimerOwes,
  type Bill,
  type BillId,
  type Claim,
  type ClaimId,
  type Tab,
  type TabMember,
} from "@owez/shared";
import { getFirebase } from "./firebase";

/**
 * Data access for bills + claims.
 *
 * Identifiers: billId is a crypto.randomUUID(). Item ids are short ids from
 * makeId(). Claim doc ids are auto-generated by Firestore — each claim
 * stores its `claimerId` as a field, which the security rules pin to
 * `request.auth.uid`.
 */

export function newBillId(): BillId {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789";
  let id = "";
  const bytes = crypto.getRandomValues(new Uint8Array(10));
  for (const b of bytes) id += chars[b % chars.length];
  return id;
}

export function makeId(): string {
  // Short id for line items — UUID is overkill here. 8 url-safe chars.
  return Math.random().toString(36).slice(2, 10);
}

/** Write a new bill doc. The caller must already be signed in with a real user. */
export async function createBill(bill: Bill): Promise<void> {
  const { db } = getFirebase();
  await setDoc(doc(db, "bills", bill.id), bill);
}

/** Update an existing bill (creator only, enforced by rules). */
export async function updateBill(bill: Bill): Promise<void> {
  const { db } = getFirebase();
  await setDoc(doc(db, "bills", bill.id), bill);
}

export async function deleteBill(billId: BillId): Promise<void> {
  const { db } = getFirebase();
  await deleteDoc(doc(db, "bills", billId));
}

/** Subscribe to a bill doc. Returns an unsubscribe function. */
export function subscribeToBill(
  billId: BillId,
  onChange: (bill: Bill | null) => void,
): Unsubscribe {
  const { db } = getFirebase();
  return onSnapshot(doc(db, "bills", billId), (snap) => {
    if (!snap.exists()) {
      onChange(null);
      return;
    }
    onChange(fromFirestore(snap.data()));
  });
}

/**
 * Subscribe to every bill the given user has created, newest first.
 *
 * The error callback fires when the composite index is still building after
 * a fresh deploy — callers should treat that as an empty list rather than
 * hanging on "Loading…" forever. Once the index finishes materializing the
 * listener will succeed on its own.
 */
export function subscribeToMyBills(
  creatorId: string,
  onChange: (bills: Bill[]) => void,
  onError?: (err: Error) => void,
): Unsubscribe {
  const { db } = getFirebase();
  const q = query(
    collection(db, "bills"),
    where("creatorId", "==", creatorId),
    orderBy("createdAt", "desc"),
  );
  return onSnapshot(
    q,
    (snap) => {
      const bills: Bill[] = [];
      snap.forEach((d) => bills.push(fromFirestore(d.data())));
      onChange(bills);
    },
    (err) => onError?.(err),
  );
}

/** Subscribe to every claim on a bill as a flat array. */
export function subscribeToClaims(
  billId: BillId,
  onChange: (claims: Claim[]) => void,
): Unsubscribe {
  const { db } = getFirebase();
  const q = query(
    collection(db, "bills", billId, "claims"),
    orderBy("createdAt", "asc"),
  );
  return onSnapshot(q, (snap) => {
    const claims: Claim[] = snap.docs.map((d) => claimFromDoc(d.id, d.data()));
    onChange(claims);
  });
}

/** One-shot fetch of claims — used by dashboard for aggregated totals. */
export async function getClaimsOnce(billId: BillId): Promise<Claim[]> {
  const { db } = getFirebase();
  const snap = await getDocs(collection(db, "bills", billId, "claims"));
  return snap.docs.map((d) => claimFromDoc(d.id, d.data()));
}

/**
 * Create a new claim on a specific (itemId, unitIndex) pair. Validates
 * against existing claims on the same unit first so concurrent writes can't
 * over-subscribe. Not a true transaction — Firestore's web SDK can't
 * transactionally read a collection — but the race window is narrow enough
 * for the scale we care about.
 */
export async function claimItemUnit(
  billId: BillId,
  data: Omit<Claim, "id" | "createdAt">,
): Promise<ClaimId> {
  const { db } = getFirebase();
  const claimsCol = collection(db, "bills", billId, "claims");

  // Pre-flight conflict check.
  const snap = await getDocs(claimsCol);
  const onUnit = snap.docs
    .map((d) => claimFromDoc(d.id, d.data()))
    .filter(
      (c) => c.itemId === data.itemId && c.unitIndex === data.unitIndex,
    );
  assertClaimAllowed(onUnit, {
    portions: data.portions,
    splitInto: data.splitInto,
    duplicate: data.duplicate,
  });

  const payload: Record<string, unknown> = {
    itemId: data.itemId,
    unitIndex: data.unitIndex,
    portions: data.portions,
    splitInto: data.splitInto,
    claimerId: data.claimerId,
    name: data.name,
    initials: data.initials,
    createdAt: Date.now(),
  };
  if (data.photoURL) payload.photoURL = data.photoURL;
  if (data.duplicate) payload.duplicate = true;

  const ref = await addDoc(claimsCol, payload);
  return ref.id;
}

/** Update an existing claim's portions/splitInto. Rules allow the claimer only. */
export async function updateClaimDoc(
  billId: BillId,
  claimId: ClaimId,
  data: { portions: number; splitInto: number },
): Promise<void> {
  const { db } = getFirebase();
  await updateDoc(doc(db, "bills", billId, "claims", claimId), data);
}

/** Delete a single claim doc. Rules allow the claimer or the bill creator. */
export async function deleteClaimDoc(
  billId: BillId,
  claimId: ClaimId,
): Promise<void> {
  const { db } = getFirebase();
  await deleteDoc(doc(db, "bills", billId, "claims", claimId));
}

/* ---------- Tab functions ---------- */

/** Write a new tab doc. The caller must be signed in with a real user. */
export async function createTab(tab: Tab): Promise<void> {
  const { db } = getFirebase();
  await setDoc(doc(db, "tabs", tab.id), tab);
}

/** Update an existing tab (creator only, enforced by rules). */
export async function updateTab(tab: Tab): Promise<void> {
  const { db } = getFirebase();
  await setDoc(doc(db, "tabs", tab.id), tab);
}

/**
 * Add a member to a tab if they're not already on it. Idempotent — safe to
 * call on every claim. Returns the updated member list (or the existing one
 * if no change was needed) so callers can keep local state in sync.
 *
 * Uses arrayUnion so concurrent claimers don't clobber each other's writes.
 * Security rules allow any signed-in member to append themselves.
 */
export async function addMemberToTab(
  tabId: string,
  member: TabMember,
): Promise<void> {
  const { db } = getFirebase();
  await updateDoc(doc(db, "tabs", tabId), {
    members: arrayUnion(member),
    updatedAt: Date.now(),
  });
}

/** Delete a tab doc (creator only, enforced by rules). */
export async function deleteTab(tabId: string): Promise<void> {
  const { db } = getFirebase();
  await deleteDoc(doc(db, "tabs", tabId));
}

/** Subscribe to a tab doc. Returns an unsubscribe function. */
export function subscribeToTab(
  tabId: string,
  onChange: (tab: Tab | null) => void,
): Unsubscribe {
  const { db } = getFirebase();
  return onSnapshot(doc(db, "tabs", tabId), (snap) => {
    if (!snap.exists()) {
      onChange(null);
      return;
    }
    onChange(tabFromFirestore(snap.data()));
  });
}

/**
 * Subscribe to every tab the given user has created, newest first.
 */
export function subscribeToMyTabs(
  creatorId: string,
  onChange: (tabs: Tab[]) => void,
  onError?: (err: Error) => void,
): Unsubscribe {
  const { db } = getFirebase();
  const q = query(
    collection(db, "tabs"),
    where("creatorId", "==", creatorId),
    orderBy("createdAt", "desc"),
  );
  return onSnapshot(
    q,
    (snap) => {
      const tabs: Tab[] = [];
      snap.forEach((d) => tabs.push(tabFromFirestore(d.data())));
      onChange(tabs);
    },
    (err) => onError?.(err),
  );
}

/** Fetch all bills on a tab. */
export async function getBillsInTab(tabId: string): Promise<Bill[]> {
  const { db } = getFirebase();
  const q = query(
    collection(db, "bills"),
    where("tabId", "==", tabId),
    orderBy("createdAt", "asc"),
  );
  const snap = await getDocs(q);
  return snap.docs.map((d) => fromFirestore(d.data()));
}

/** Subscribe to all bills on a tab, ordered by creation date. */
export function subscribeToBillsInTab(
  tabId: string,
  onChange: (bills: Bill[]) => void,
): Unsubscribe {
  const { db } = getFirebase();
  const q = query(
    collection(db, "bills"),
    where("tabId", "==", tabId),
    orderBy("createdAt", "asc"),
  );
  return onSnapshot(q, (snap) => {
    const bills: Bill[] = snap.docs.map((d) => fromFirestore(d.data()));
    onChange(bills);
  });
}

/**
 * Fetch all claims across all bills on a tab.
 * Used for settlement calculation.
 */
export async function getClaimsInTab(tabId: string): Promise<Claim[]> {
  const { db } = getFirebase();
  const bills = await getBillsInTab(tabId);
  const allClaims: Claim[] = [];

  for (const bill of bills) {
    const snap = await getDocs(collection(db, "bills", bill.id, "claims"));
    snap.docs.forEach((d) => {
      allClaims.push(claimFromDoc(d.id, d.data()));
    });
  }

  return allClaims;
}

/**
 * Calculate settlement amounts for a tab: who owes whom across all receipts.
 * For each member, nets what they owe for bills the current user created
 * against what the current user owes for bills that member created.
 * Returns a map of userId → {owesYou, youOwe} from the current user's view.
 *
 * Claims are matched to their bill by item membership: a claim belongs to a
 * bill when the bill contains an item with the claim's itemId. Item ids are
 * unique across bills (makeId), so this is unambiguous.
 */
export function tabSettlement(
  tab: Tab,
  bills: Bill[],
  claims: Claim[],
  currentUserId: string,
): Record<string, { owesYou: number; youOwe: number }> {
  const settlement: Record<string, { owesYou: number; youOwe: number }> = {};

  // Initialize settlement for all tab members
  for (const member of tab.members) {
    if (member.userId !== currentUserId) {
      settlement[member.userId] = { owesYou: 0, youOwe: 0 };
    }
  }

  for (const member of tab.members) {
    if (member.userId === currentUserId) continue;
    const entry = settlement[member.userId];
    if (!entry) continue;

    for (const bill of bills) {
      const billClaims = claims.filter((c) =>
        bill.items.some((item) => item.id === c.itemId)
      );

      // Bills I created: sum what this member owes me.
      if (bill.creatorId === currentUserId) {
        entry.owesYou += claimerOwes(bill, billClaims, member.userId).totalCents;
      }
      // Bills they created: sum what I owe them.
      if (bill.creatorId === member.userId) {
        entry.youOwe += claimerOwes(bill, billClaims, currentUserId).totalCents;
      }
    }
  }

  // Remove zero balances
  for (const userId of Object.keys(settlement)) {
    const entry = settlement[userId];
    if (entry && entry.owesYou === 0 && entry.youOwe === 0) {
      delete settlement[userId];
    }
  }

  return settlement;
}

/* ---------- Firestore ↔ TS shape glue ---------- */

function fromFirestore(data: Record<string, unknown>): Bill {
  const createdAt =
    data.createdAt instanceof Timestamp
      ? data.createdAt.toMillis()
      : typeof data.createdAt === "number"
        ? data.createdAt
        : Date.now();

  return {
    id: String(data.id ?? ""),
    creatorId: String(data.creatorId ?? ""),
    creatorName:
      typeof data.creatorName === "string" ? data.creatorName : undefined,
    creatorPhotoURL:
      typeof data.creatorPhotoURL === "string"
        ? data.creatorPhotoURL
        : undefined,
    createdAt,
    title: typeof data.title === "string" ? data.title : undefined,
    items: Array.isArray(data.items) ? (data.items as Bill["items"]) : [],
    subtotalCents: Number(data.subtotalCents ?? 0),
    taxCents: Number(data.taxCents ?? 0),
    tipCents: Number(data.tipCents ?? 0),
    totalCents: Number(data.totalCents ?? 0),
    paymentMethods:
      (data.paymentMethods as Bill["paymentMethods"] | undefined) ?? {},
    tabId: typeof data.tabId === "string" ? data.tabId : undefined,
  };
}

function tabFromFirestore(data: Record<string, unknown>): Tab {
  const createdAt =
    data.createdAt instanceof Timestamp
      ? data.createdAt.toMillis()
      : typeof data.createdAt === "number"
        ? data.createdAt
        : Date.now();

  const updatedAt =
    data.updatedAt instanceof Timestamp
      ? data.updatedAt.toMillis()
      : typeof data.updatedAt === "number"
        ? data.updatedAt
        : undefined;

  return {
    id: String(data.id ?? ""),
    creatorId: String(data.creatorId ?? ""),
    creatorName:
      typeof data.creatorName === "string" ? data.creatorName : undefined,
    creatorPhotoURL:
      typeof data.creatorPhotoURL === "string"
        ? data.creatorPhotoURL
        : undefined,
    createdAt,
    title: String(data.title ?? ""),
    description:
      typeof data.description === "string" ? data.description : undefined,
    members: Array.isArray(data.members)
      ? (data.members as TabMember[])
      : [],
    receiptIds: Array.isArray(data.receiptIds)
      ? data.receiptIds.map((x) => String(x))
      : [],
    status:
      data.status === "settled" ? "settled" : ("active" as const),
    updatedAt,
  };
}

function claimFromDoc(id: string, data: Record<string, unknown>): Claim {
  return {
    id,
    itemId: String(data.itemId ?? ""),
    unitIndex: Number(data.unitIndex ?? 0),
    portions: Number(data.portions ?? 1),
    splitInto: Number(data.splitInto ?? 1),
    claimerId: String(data.claimerId ?? ""),
    name: typeof data.name === "string" ? data.name : "",
    initials: typeof data.initials === "string" ? data.initials : "",
    createdAt:
      data.createdAt instanceof Timestamp
        ? data.createdAt.toMillis()
        : typeof data.createdAt === "number"
          ? data.createdAt
          : Date.now(),
    photoURL: typeof data.photoURL === "string" ? data.photoURL : undefined,
    duplicate: data.duplicate === true ? true : undefined,
  };
}
